### ISSUE TITLE
Type hint for `url` @register_url missing dict as option

### ISSUE THREAD

**Issue by peterfarrell** [Privex/adminplus#1]
The `register_url` decorator is missing  Dict as an option:

Should read:

```python
def register_url(url: Union[str, List[str], Dict[str, str]] = None, human: str = None, hidden: bool = False, name: str = None, **kwargs):
```

**Comment by Someguy123** [comment]
Thanks for letting us know - I've fixed the type annotations for the various URL registration functions/decorators/methods, and I've pushed it out as 0.9.3

It's now available on PyPi, just run `pip3 install -U 'privex-adminplus==0.9.3'` to grab the patch 👍

**Comment by peterfarrell** [comment]
@Someguy123 Works great and our linter is no longer complaining. Thank you for the swift release!
